name: IaC Security Scan

on:
  push:
  pull_request:

jobs:
  terraform-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Run Trivy IaC Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: config
          scan-ref: ./iac-terraform-sec
          severity: HIGH,CRITICAL
          exit-code: 1

      - name: Terraform Init & Validate
        run: |
          cd iac-terraform-sec
          terraform init -backend=false
          terraform validate

  ansible-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ansible & ansible-lint
        run: |
          sudo apt update
          sudo apt install -y ansible python3-pip
          pip3 install --user ansible-lint

      - name: Run ansible-lint
        run: |
          cd ansible-sec
          ansible-lint .

